# -*- coding: utf-8 -*-
"""
/***************************************************************************
 cliplayers
                                 A QGIS plugin
 表示は範囲をGeoPackageにエクスポートする
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-04-28
        copyright            : (C) 2020 by インクリメントP株式会社
        email                : yonezawa@incrementp.co.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load cliplayers class from file cliplayers.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cliplayers import cliplayers
    return cliplayers(iface)
